### ISSUE TITLE
When creating nodes of another type, the legend will always show Personalizado(Conceito) before the types of the nodes

### ISSUE THREAD

**Issue by nmellouli** [heritamus/Heritamus#6] opened 2018-06-12 20:35 UTC
when creating a new graph, 
<img width="1672" alt="capture_d_ecran_2018-06-11_a_11 40 41" src="https://user-images.githubusercontent.com/25639914/41315795-dc572b08-6e90-11e8-8a60-06abe592b35c.png">

**Comment by heritamus** [comment] 2018-06-20 14:53
duplicate of gitlab

**Closed as completed by heritamus** 2018-06-20 14:53 UTC
